apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: c3td0tfag-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:aa25cd0959efb33fcd371f84c5e5e7ce32dead3e@sha256:329c531766ed0e7f3a08f7efe72176ecdfc822d617e6b21d96b1bc0b90a41f95
          name: container-image
